// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protodata.proto

package food

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FoodTypes struct {
	Fruit                string   `protobuf:"bytes,1,opt,name=fruit" json:"fruit,omitempty"`
	Vegetable            string   `protobuf:"bytes,2,opt,name=vegetable" json:"vegetable,omitempty"`
	Carbs                string   `protobuf:"bytes,3,opt,name=carbs" json:"carbs,omitempty"`
	Protein              string   `protobuf:"bytes,4,opt,name=protein" json:"protein,omitempty"`
	Desert               string   `protobuf:"bytes,5,opt,name=desert" json:"desert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoodTypes) Reset()         { *m = FoodTypes{} }
func (m *FoodTypes) String() string { return proto.CompactTextString(m) }
func (*FoodTypes) ProtoMessage()    {}
func (*FoodTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_protodata_adb8d61c30d95e8b, []int{0}
}
func (m *FoodTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodTypes.Unmarshal(m, b)
}
func (m *FoodTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodTypes.Marshal(b, m, deterministic)
}
func (dst *FoodTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodTypes.Merge(dst, src)
}
func (m *FoodTypes) XXX_Size() int {
	return xxx_messageInfo_FoodTypes.Size(m)
}
func (m *FoodTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodTypes.DiscardUnknown(m)
}

var xxx_messageInfo_FoodTypes proto.InternalMessageInfo

func (m *FoodTypes) GetFruit() string {
	if m != nil {
		return m.Fruit
	}
	return ""
}

func (m *FoodTypes) GetVegetable() string {
	if m != nil {
		return m.Vegetable
	}
	return ""
}

func (m *FoodTypes) GetCarbs() string {
	if m != nil {
		return m.Carbs
	}
	return ""
}

func (m *FoodTypes) GetProtein() string {
	if m != nil {
		return m.Protein
	}
	return ""
}

func (m *FoodTypes) GetDesert() string {
	if m != nil {
		return m.Desert
	}
	return ""
}

func init() {
	proto.RegisterType((*FoodTypes)(nil), "food.foodTypes")
}

func init() { proto.RegisterFile("protodata.proto", fileDescriptor_protodata_adb8d61c30d95e8b) }

var fileDescriptor_protodata_adb8d61c30d95e8b = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x49, 0x2c, 0x49, 0xd4, 0x03, 0xb3, 0x84, 0x58, 0xd2, 0xf2, 0xf3, 0x53, 0x94, 0xda,
	0x19, 0xb9, 0x38, 0x41, 0x8c, 0x90, 0xca, 0x82, 0xd4, 0x62, 0x21, 0x11, 0x2e, 0xd6, 0xb4, 0xa2,
	0xd2, 0xcc, 0x12, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0x47, 0x48, 0x86, 0x8b, 0xb3,
	0x2c, 0x35, 0x3d, 0xb5, 0x24, 0x31, 0x29, 0x27, 0x55, 0x82, 0x09, 0x2c, 0x83, 0x10, 0x00, 0xe9,
	0x49, 0x4e, 0x2c, 0x4a, 0x2a, 0x96, 0x60, 0x86, 0xe8, 0x01, 0x73, 0x84, 0x24, 0xb8, 0xd8, 0x41,
	0xd6, 0xa4, 0x66, 0xe6, 0x49, 0xb0, 0x80, 0xc5, 0x61, 0x5c, 0x21, 0x31, 0x2e, 0xb6, 0x94, 0xd4,
	0xe2, 0xd4, 0xa2, 0x12, 0x09, 0x56, 0xb0, 0x04, 0x94, 0x97, 0xc4, 0x06, 0x76, 0x96, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x6c, 0xbb, 0xc8, 0x87, 0xa9, 0x00, 0x00, 0x00,
}
